import { LEGAL_SOURCE_MANIFEST_VERSION } from "./legalSources";
import type { ControlDefinition, ControlStatus, VerificationClass } from "./types";

const SV = LEGAL_SOURCE_MANIFEST_VERSION;

const ALL_STATUS: ControlStatus[] = [
  "VERIFIED",
  "VIOLATED",
  "PARTIAL",
  "NOT_OBSERVED",
  "NEEDS_CONTEXT",
  "NOT_APPLICABLE",
  "SKIPPED",
  "ERROR"
];

function control(
  partial: Omit<ControlDefinition, "sourceVersion" | "possibleStatuses"> & {
    possibleStatuses?: ControlStatus[];
    sourceVersion?: string;
  }
): ControlDefinition {
  return {
    possibleStatuses: ALL_STATUS,
    sourceVersion: SV,
    ...partial
  };
}

/**
 * Machine-readable DPDP obligation catalogue for technical readiness assessment.
 * Every control has verification class, legal reference, and evaluator linkage where deterministic.
 */
export const DPDP_CONTROLS: ControlDefinition[] = [
  control({
    id: "DPDP-APP-001",
    title: "Personal data processing inventory from code",
    domain: "applicability_and_inventory",
    technicalIntent: "Identify whether the codebase appears to collect, store, or transmit personal data.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 2 (definitions)", "Section 3 (application)"],
    applicability: { when: "Always for application codebases", requiresPersonalData: false },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Detected personal-data categories, fields, or collection points"],
    evaluatorId: "inventory-personal-data",
    severityRules: { defaultSeverity: "info", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Cannot prove absence of personal data outside scanned paths"],
    remediation: "Document data categories and ensure inventory matches implementation surfaces.",
    humanReviewQuestions: ["Does the product process personal data outside this repository?"]
  }),
  control({
    id: "DPDP-APP-002",
    title: "Applicability determination requires organisational context",
    domain: "exemptions_and_applicability",
    technicalIntent: "Flag when legal applicability cannot be established from code alone.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-ENFORCEMENT-NOTIFICATION"],
    legalCitations: ["Section 3", "Section 17", "Enforcement notification"],
    applicability: { when: "Always" },
    verificationClass: "HUMAN_REVIEW",
    evidenceRequirements: ["Declared organisation context or legal determination"],
    severityRules: { defaultSeverity: "info", violatedSeverity: "info" },
    limitations: ["Legal applicability is not a code property"],
    remediation: "Record organisation context in .vibedoctor/dpdp/context.yml and obtain legal review where needed.",
    humanReviewQuestions: [
      "Is the organisation a Data Fiduciary under DPDP for this processing?",
      "Do any statutory exemptions apply?"
    ]
  }),
  control({
    id: "DPDP-NOTICE-001",
    title: "Notice presentation technical signal",
    domain: "notice",
    technicalIntent: "Detect implementation signals for privacy notice / notice versioning.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 5", "Rules: Notice requirements"],
    applicability: { when: "When personal data is collected", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Notice templates, notice version fields, privacy policy routes"],
    evaluatorId: "notice-signals",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Notice adequacy and language quality require human review"],
    remediation: "Implement notice delivery at collection points with version tracking.",
    humanReviewQuestions: ["Is the notice itemised, clear, and presented before or at collection?"]
  }),
  control({
    id: "DPDP-CONSENT-001",
    title: "Consent capture implementation",
    domain: "consent",
    technicalIntent: "Detect consent capture APIs, flags, or records in code/schema.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 6"],
    applicability: { when: "When processing relies on consent", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Consent fields, endpoints, or SDKs"],
    evaluatorId: "consent-capture",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high", partialSeverity: "medium" },
    limitations: ["Cannot verify free, specific, informed, unconditional consent quality"],
    remediation: "Implement explicit consent capture with purpose binding before processing.",
    humanReviewQuestions: ["Is consent free, specific, informed, unconditional and unambiguous?"]
  }),
  control({
    id: "DPDP-CONSENT-002",
    title: "Consent metadata completeness",
    domain: "consent",
    technicalIntent: "Require timestamp, purpose identifier, and notice version when consent is stored.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 6", "Rules: consent records"],
    applicability: { when: "When consent capture signals exist", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Consent model fields for timestamp, purpose, notice version"],
    evaluatorId: "consent-metadata",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Schema signals may not reflect runtime consent manager behaviour"],
    remediation: "Store consent_given_at, purpose_id, and notice_version with each consent record.",
    humanReviewQuestions: ["Who is the system of record for consent proofs?"]
  }),
  control({
    id: "DPDP-WITHDRAW-001",
    title: "Consent withdrawal path",
    domain: "withdrawal",
    technicalIntent: "Detect withdrawal/opt-out endpoints or equivalent flows.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 6(4)"],
    applicability: { when: "When consent-based processing is present", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Withdrawal endpoints, unsubscribe, revoke consent handlers"],
    evaluatorId: "consent-withdrawal",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high", partialSeverity: "medium" },
    limitations: ["Ease of withdrawal relative to grant requires UX review"],
    remediation: "Provide a withdrawal API/UI that is as easy as giving consent and propagates to processors.",
    humanReviewQuestions: ["Can a Data Principal withdraw consent as easily as they gave it?"]
  }),
  control({
    id: "DPDP-PURPOSE-001",
    title: "Purpose identifier technical binding",
    domain: "purpose_limitation",
    technicalIntent: "Detect purpose identifiers bound to collection or consent records.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 4", "Section 6", "Section 8"],
    applicability: { when: "When personal data is processed", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["purpose_id fields, purpose enums, purpose-tagged pipelines"],
    evaluatorId: "purpose-binding",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Secondary use policies cannot be fully validated statically"],
    remediation: "Tag processing pipelines and consent with purpose identifiers and enforce purpose checks.",
    humanReviewQuestions: ["Are purposes limited to those disclosed at collection?"]
  }),
  control({
    id: "DPDP-MIN-001",
    title: "API over-fetching of personal data objects",
    domain: "data_minimisation",
    technicalIntent: "Detect whole user/customer objects returned from APIs without projection.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 8 (data minimisation principle via fiduciary duties)"],
    applicability: { when: "When personal data APIs exist", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["API handlers serialising full user objects"],
    evaluatorId: "api-overfetch",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium" },
    limitations: ["Cannot prove field necessity for every business case"],
    remediation: "Return DTOs with explicit field selection rather than whole entities.",
    humanReviewQuestions: ["Is each returned field necessary for the stated purpose?"]
  }),
  control({
    id: "DPDP-MIN-002",
    title: "Broad database selection of personal records",
    domain: "data_minimisation",
    technicalIntent: "Detect SELECT * or unscoped findMany on personal-data models.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 8"],
    applicability: { when: "When ORM/SQL access to personal data exists", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Broad query patterns on user/customer models"],
    evaluatorId: "broad-db-select",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Some admin tooling legitimately needs broad reads"],
    remediation: "Scope queries and project only required columns for each use case.",
    humanReviewQuestions: ["Which roles need full-record access and why?"]
  }),
  control({
    id: "DPDP-ACC-001",
    title: "Accuracy and correction technical path",
    domain: "accuracy",
    technicalIntent: "Detect correction/update endpoints for personal data profiles.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 12"],
    applicability: { when: "When personal data is stored", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Profile update/correction routes"],
    evaluatorId: "correction-path",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Downstream processor propagation not fully visible"],
    remediation: "Implement authenticated correction flows and cascade updates to processors.",
    humanReviewQuestions: ["How are inaccurate records corrected across processors?"]
  }),
  control({
    id: "DPDP-SEC-001",
    title: "PII in application logs",
    domain: "security_safeguards",
    technicalIntent: "Detect unsanitized personal data written to logs.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Rules: reasonable security safeguards"],
    applicability: { when: "When personal data is processed", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Logger calls with PII keywords or values"],
    evaluatorId: "pii-in-logs",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high" },
    limitations: ["Dynamic log payloads may evade static detection"],
    remediation: "Redact or structure-log with allowlists; never log raw identifiers.",
    humanReviewQuestions: ["What is the log retention and access control policy?"]
  }),
  control({
    id: "DPDP-SEC-002",
    title: "PII in LLM prompts or embeddings",
    domain: "security_safeguards",
    technicalIntent: "Detect personal data sent to LLM APIs, prompts, or vector stores.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Section 16"],
    applicability: { when: "When LLM or embedding integrations exist", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Prompt construction with user fields; embedding upserts of personal text"],
    evaluatorId: "pii-in-llm",
    severityRules: { defaultSeverity: "high", violatedSeverity: "critical" },
    limitations: ["Runtime prompt assembly may be indirect"],
    remediation: "Minimise/redact PII before model calls; document processor terms for AI vendors.",
    humanReviewQuestions: ["Are LLM providers acting as processors under contract?"]
  }),
  control({
    id: "DPDP-SEC-003",
    title: "PII in URLs or query strings",
    domain: "security_safeguards",
    technicalIntent: "Detect personal data placed in URL paths or query parameters.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8"],
    applicability: { when: "When HTTP APIs handle personal data", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Route templates or URL builders with email/phone/aadhaar tokens"],
    evaluatorId: "pii-in-urls",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high" },
    limitations: ["Server logs of URLs may still capture PII even if code is fixed later"],
    remediation: "Move identifiers into authenticated request bodies or opaque tokens.",
    humanReviewQuestions: ["Are access logs scrubbed of query-string PII?"]
  }),
  control({
    id: "DPDP-SEC-004",
    title: "Browser storage of personal data",
    domain: "security_safeguards",
    technicalIntent: "Detect localStorage/sessionStorage/cookie storage of personal data.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8"],
    applicability: { when: "When client-side storage is used", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Browser storage writes of email/phone/tokens with PII"],
    evaluatorId: "browser-storage-pii",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "high", partialSeverity: "medium" },
    limitations: ["HttpOnly cookie policy requires runtime/config review"],
    remediation: "Avoid storing raw PII in browser storage; prefer short-lived opaque session tokens.",
    humanReviewQuestions: ["What is the XSS residual risk for client-stored personal data?"]
  }),
  control({
    id: "DPDP-SEC-005",
    title: "Insecure HTTP transmission of personal data",
    domain: "security_safeguards",
    technicalIntent: "Detect cleartext HTTP endpoints used with personal-data APIs.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Rules: security safeguards"],
    applicability: { when: "When network transmission of personal data exists", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["http:// URLs for APIs handling personal data"],
    evaluatorId: "insecure-http",
    severityRules: { defaultSeverity: "high", violatedSeverity: "critical" },
    limitations: ["TLS termination outside repo is not visible"],
    remediation: "Use HTTPS for all personal-data transport; enforce HSTS where applicable.",
    humanReviewQuestions: ["Is TLS terminated and re-encrypted correctly in production?"]
  }),
  control({
    id: "DPDP-SEC-006",
    title: "Authentication on personal-data routes",
    domain: "security_safeguards",
    technicalIntent: "Detect personal-data routes lacking auth middleware signals.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8"],
    applicability: { when: "When personal-data routes exist", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Route definitions with/without auth middleware"],
    evaluatorId: "route-auth",
    severityRules: { defaultSeverity: "high", violatedSeverity: "critical", partialSeverity: "high" },
    limitations: ["Framework-global auth guards may be invisible to local patterns"],
    remediation: "Apply authentication and authorisation middleware to all personal-data endpoints.",
    humanReviewQuestions: ["Is object-level authorisation enforced for every principal resource?"]
  }),
  control({
    id: "DPDP-SEC-007",
    title: "Hardcoded production personal data or sensitive fixtures",
    domain: "security_safeguards",
    technicalIntent: "Detect high-confidence identifier values embedded in source/fixtures.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8"],
    applicability: { when: "Always when personal data values appear in repo", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["Regulated identifiers or realistic PII values in code"],
    evaluatorId: "hardcoded-pii",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high" },
    limitations: ["Synthetic test data may look real"],
    remediation: "Replace with clearly synthetic fixtures; never commit production personal data.",
    humanReviewQuestions: ["Are any committed values real production identifiers?"]
  }),
  control({
    id: "DPDP-SEC-008",
    title: "Debug endpoints exposing personal records",
    domain: "security_safeguards",
    technicalIntent: "Detect debug/admin dump endpoints returning user records.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8"],
    applicability: { when: "When debug routes exist near personal data", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["debug/dump routes returning users"],
    evaluatorId: "debug-exposure",
    severityRules: { defaultSeverity: "critical", violatedSeverity: "critical" },
    limitations: ["Environment gating may not be visible statically"],
    remediation: "Remove or strictly gate debug endpoints; never expose personal dumps in production.",
    humanReviewQuestions: ["Are debug routes disabled in production deployments?"]
  }),
  control({
    id: "DPDP-SEC-009",
    title: "Weak or reversible masking of identifiers",
    domain: "security_safeguards",
    technicalIntent: "Detect trivial masking that preserves most of the identifier.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8"],
    applicability: { when: "When masking helpers exist", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Masking functions that only hide 1-2 characters"],
    evaluatorId: "weak-masking",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium" },
    limitations: ["Context-specific display masking may be acceptable"],
    remediation: "Use irreversible hashing or strong partial masking for logs and non-essential displays.",
    humanReviewQuestions: ["Is masking used for security or only for display convenience?"]
  }),
  control({
    id: "DPDP-SEC-010",
    title: "Missing audit signals on sensitive personal-data operations",
    domain: "security_safeguards",
    technicalIntent: "Detect export/delete/admin personal-data operations without audit logging signals.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Section 10"],
    applicability: { when: "When sensitive personal-data operations exist", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["Sensitive ops with/without audit trail calls"],
    evaluatorId: "audit-signals",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["External SIEM integration may not appear in app code"],
    remediation: "Emit immutable audit events for access, export, correction, deletion, and admin overrides.",
    humanReviewQuestions: ["Where are audit logs retained and who can access them?"]
  }),
  control({
    id: "DPDP-BREACH-001",
    title: "Personal-data breach preparedness signals",
    domain: "breach_preparedness",
    technicalIntent: "Detect incident/breach runbooks, alerting hooks, or notification templates.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Rules: personal data breach"],
    applicability: { when: "When personal data is processed", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["breach/incident handlers, runbooks, notification templates"],
    evaluatorId: "breach-preparedness",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Operational readiness cannot be proven from code alone"],
    remediation: "Implement breach detection hooks and documented notification workflows.",
    humanReviewQuestions: ["Is there a tested personal-data breach response plan with timelines?"]
  }),
  control({
    id: "DPDP-RET-001",
    title: "Retention or TTL mechanism for personal data stores",
    domain: "retention",
    technicalIntent: "Detect retention fields, TTL, or lifecycle configs on personal-data stores.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Rules: retention"],
    applicability: { when: "When personal data is stored", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["deletedAt/expiresAt/TTL/lifecycle config on PII stores"],
    evaluatorId: "retention-mechanism",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high", partialSeverity: "medium" },
    limitations: ["Policy periods vs technical TTL need human alignment"],
    remediation: "Add retention fields and scheduled deletion jobs matching purpose-limited periods.",
    humanReviewQuestions: ["What is the lawful retention period for each purpose?"]
  }),
  control({
    id: "DPDP-ERA-001",
    title: "Erasure / account deletion path",
    domain: "erasure",
    technicalIntent: "Detect hard/soft delete and account deletion flows for personal data.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 12"],
    applicability: { when: "When personal data is stored", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["delete account endpoints, hard delete, soft delete"],
    evaluatorId: "erasure-path",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high", partialSeverity: "medium" },
    limitations: ["Backups and processor erasure lag may be invisible"],
    remediation: "Implement verified erasure including backups/processors within stated timelines.",
    humanReviewQuestions: ["How are backups and processor copies erased after a request?"]
  }),
  control({
    id: "DPDP-ERA-002",
    title: "Retained personal data without visible deletion path",
    domain: "erasure",
    technicalIntent: "Flag personal-data storage without any deletion/TTL/erasure signals.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Section 12"],
    applicability: { when: "When personal data stores exist", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["PII stores vs deletion signals"],
    evaluatorId: "storage-without-deletion",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high" },
    limitations: ["External data warehouses may hold copies"],
    remediation: "Ensure every personal-data store has a documented and implemented deletion path.",
    humanReviewQuestions: ["Is any personal data kept indefinitely for legal holds?"]
  }),
  control({
    id: "DPDP-ACC-RIGHT-001",
    title: "Data Principal access / export endpoint",
    domain: "data_principal_access",
    technicalIntent: "Detect data export/access/download-my-data endpoints.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 11"],
    applicability: { when: "When personal data is stored", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["export/access/download routes"],
    evaluatorId: "access-export",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Completeness of export packages needs review"],
    remediation: "Provide authenticated access/export of personal data held by the fiduciary.",
    humanReviewQuestions: ["Does the export include all purposes and processors?"]
  }),
  control({
    id: "DPDP-CORR-001",
    title: "Correction request implementation",
    domain: "correction",
    technicalIntent: "Detect correction request workflows distinct from generic profile edits where present.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 12"],
    applicability: { when: "When personal data is stored", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["correction request handlers"],
    evaluatorId: "correction-path",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Operational SLAs not visible in code"],
    remediation: "Expose correction request APIs with tracking and authentication.",
    humanReviewQuestions: ["What is the turnaround SLA for correction requests?"]
  }),
  control({
    id: "DPDP-GRIEV-001",
    title: "Grievance handling technical signal",
    domain: "grievance_handling",
    technicalIntent: "Detect grievance/complaint submission and privacy contact signals.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 13"],
    applicability: { when: "When personal data is processed", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["grievance endpoints, privacy contact emails"],
    evaluatorId: "grievance-handling",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Effectiveness of redressal is operational"],
    remediation: "Publish grievance contact and implement tracked grievance intake.",
    humanReviewQuestions: ["Who is the designated grievance officer and what is the SLA?"]
  }),
  control({
    id: "DPDP-NOM-001",
    title: "Nomination-related implementation signal",
    domain: "nomination",
    technicalIntent: "Detect nomination fields or flows for Data Principal rights exercise after incapacity/death.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 14"],
    applicability: { when: "When long-lived personal accounts exist", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["nominee fields, nomination APIs"],
    evaluatorId: "nomination-signal",
    severityRules: { defaultSeverity: "low", violatedSeverity: "low", partialSeverity: "info" },
    limitations: ["Applicability depends on product context"],
    remediation: "Where relevant, support nominee registration and authenticated exercise of rights.",
    humanReviewQuestions: ["Does product context require nomination support under Section 14?"]
  }),
  control({
    id: "DPDP-CHILD-001",
    title: "Children's data processing signals",
    domain: "childrens_data",
    technicalIntent: "Detect age/DOB/child flags and child-oriented processing paths.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 9"],
    applicability: { when: "When children's data may be processed", requiresChildren: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["age gates, child flags, under-18 checks"],
    evaluatorId: "childrens-data",
    severityRules: { defaultSeverity: "high", violatedSeverity: "critical", partialSeverity: "high" },
    limitations: ["Age verification strength requires specialised review"],
    remediation: "Implement verifiable age assurance and restrict tracking/ads for children as required.",
    humanReviewQuestions: ["Does the service knowingly process children's personal data?"]
  }),
  control({
    id: "DPDP-CHILD-002",
    title: "Guardian / parental consent flow",
    domain: "guardian_consent",
    technicalIntent: "Detect guardian/parental consent implementation when children's data is present.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 9"],
    applicability: { when: "When children's data signals exist", requiresChildren: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["parental/guardian consent flows"],
    evaluatorId: "guardian-consent",
    severityRules: { defaultSeverity: "critical", violatedSeverity: "critical", partialSeverity: "high" },
    limitations: ["Identity of guardian cannot be proven statically"],
    remediation: "Implement verifiable parental/guardian consent before processing children's data.",
    humanReviewQuestions: ["How is guardian identity verified in production?"]
  }),
  control({
    id: "DPDP-PROC-001",
    title: "External processors and recipients inventory",
    domain: "processors_and_recipients",
    technicalIntent: "Detect analytics, messaging, payments, identity, cloud, and LLM processor SDKs.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 8", "definitions of Data Processor"],
    applicability: { when: "When third-party services receive personal data", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["SDK imports, API clients to third parties"],
    evaluatorId: "external-processors",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Contracts and DPAs are not in code"],
    remediation: "Maintain processor inventory and ensure contracts include processing instructions.",
    humanReviewQuestions: ["Are written contracts in place with each processor?"]
  }),
  control({
    id: "DPDP-XBR-001",
    title: "Cross-border or external-service technical signals",
    domain: "cross_border_signals",
    technicalIntent: "Detect overseas regions, foreign SaaS endpoints, or cross-border transfer config.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 16"],
    applicability: { when: "When external services or regions are configured", requiresCrossBorder: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["region configs, foreign endpoints"],
    evaluatorId: "cross-border-signals",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Actual transfer location depends on vendor routing"],
    remediation: "Document transfer destinations and align with permitted geographies / conditions.",
    humanReviewQuestions: ["Which jurisdictions receive personal data in production?"]
  }),
  control({
    id: "DPDP-SDF-001",
    title: "Significant Data Fiduciary technical obligations",
    domain: "significant_data_fiduciary",
    technicalIntent: "Detect DPO contact, independent audit hooks, and record-keeping signals if SDF applies.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 10"],
    applicability: { when: "When organisation is or may be a Significant Data Fiduciary", requiresSdf: true },
    verificationClass: "HUMAN_REVIEW",
    evidenceRequirements: ["DPO contacts, audit logging, data protection impact assessments"],
    evaluatorId: "sdf-signals",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high", partialSeverity: "medium" },
    limitations: ["SDF designation is organisational/legal, not inferred solely from code"],
    remediation: "If designated SDF, implement DPO, audits, and DPIA processes with technical evidence trails.",
    humanReviewQuestions: ["Has the organisation been notified/designated as a Significant Data Fiduciary?"]
  }),
  control({
    id: "DPDP-REQ-001",
    title: "Rights request authentication and tracking",
    domain: "data_principal_access",
    technicalIntent: "Detect authentication and ticket/tracking around principal rights requests.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 11", "Section 12", "Section 13"],
    applicability: { when: "When rights endpoints exist", requiresPersonalData: true },
    verificationClass: "TECHNICAL_SIGNAL",
    evidenceRequirements: ["request auth, request IDs, status tracking"],
    evaluatorId: "rights-request-tracking",
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium", partialSeverity: "low" },
    limitations: ["Identity proofing strength needs human review"],
    remediation: "Authenticate requesters and track request lifecycle to completion.",
    humanReviewQuestions: ["How is Data Principal identity verified for rights requests?"]
  }),
  control({
    id: "DPDP-EXPORT-001",
    title: "Unprotected personal-data exports",
    domain: "security_safeguards",
    technicalIntent: "Detect export endpoints without auth or with broad dump behaviour.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 8", "Section 11"],
    applicability: { when: "When export endpoints exist", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["export handlers lacking auth signals"],
    evaluatorId: "unprotected-export",
    severityRules: { defaultSeverity: "critical", violatedSeverity: "critical" },
    limitations: ["Gateway-level auth may be external"],
    remediation: "Require strong authentication and authorisation on all personal-data exports.",
    humanReviewQuestions: ["Who can export personal data in production and how is it logged?"]
  }),
  control({
    id: "DPDP-NOTICE-002",
    title: "Notice and consent adequacy (human review)",
    domain: "notice",
    technicalIntent: "Capture that notice/consent legal adequacy cannot be certified from code.",
    legalSourceIds: ["DPDP-ACT-2023", "DPDP-RULES-2025"],
    legalCitations: ["Section 5", "Section 6"],
    applicability: { when: "When personal data is collected", requiresPersonalData: true },
    verificationClass: "HUMAN_REVIEW",
    evidenceRequirements: ["Policy documents, UX flows, language review"],
    severityRules: { defaultSeverity: "info", violatedSeverity: "info" },
    limitations: ["Outside deterministic scope"],
    remediation: "Commission product/legal review of notices and consent UX.",
    humanReviewQuestions: [
      "Does notice describe purposes, rights, and grievance contact clearly?",
      "Is consent itemised for distinct purposes?"
    ]
  }),
  control({
    id: "DPDP-PROC-002",
    title: "Processor contracts and instructions (human review)",
    domain: "processors_and_recipients",
    technicalIntent: "Ensure processor contractual arrangements are reviewed outside code.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 8"],
    applicability: { when: "When processors are used", requiresProcessors: true },
    verificationClass: "DECLARED_EVIDENCE",
    evidenceRequirements: ["Declared contracts / DPAs in evidence.yml"],
    severityRules: { defaultSeverity: "medium", violatedSeverity: "medium" },
    limitations: ["Contracts are not executable evidence"],
    remediation: "Attach processor contract references as declared evidence; never treat as deterministic pass.",
    humanReviewQuestions: ["Do contracts bind processors to fiduciary instructions and security?"]
  }),
  control({
    id: "DPDP-THIRD-001",
    title: "Whole user objects sent to third parties",
    domain: "processors_and_recipients",
    technicalIntent: "Detect shipping full user objects to analytics/error/LLM vendors.",
    legalSourceIds: ["DPDP-ACT-2023"],
    legalCitations: ["Section 8"],
    applicability: { when: "When third-party SDKs exist", requiresPersonalData: true },
    verificationClass: "DETERMINISTIC",
    evidenceRequirements: ["SDK calls with user objects"],
    evaluatorId: "third-party-user-object",
    severityRules: { defaultSeverity: "high", violatedSeverity: "high" },
    limitations: ["SDK auto-PII collection may be config-driven"],
    remediation: "Send only necessary attributes; scrub PII before third-party calls.",
    humanReviewQuestions: ["What data categories does each vendor actually receive?"]
  })
];

export function getControlById(id: string): ControlDefinition | undefined {
  return DPDP_CONTROLS.find((controlDef) => controlDef.id === id);
}

export function controlsByDomain(): Record<string, ControlDefinition[]> {
  const grouped: Record<string, ControlDefinition[]> = {};
  for (const item of DPDP_CONTROLS) {
    grouped[item.domain] = grouped[item.domain] ?? [];
    grouped[item.domain].push(item);
  }
  return grouped;
}

export function controlsForVerificationClass(vc: VerificationClass): ControlDefinition[] {
  return DPDP_CONTROLS.filter((controlDef) => controlDef.verificationClass === vc);
}

export const DPDP_CATALOGUE_META = {
  version: SV,
  controlCount: DPDP_CONTROLS.length,
  disclaimer:
    "This catalogue supports DPDP technical readiness and engineering-risk assessment. It is not a legal certification instrument."
};
